/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.naming.ldap.Rdn;

/**
 *
 * @author Adriano Pavaneli
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        RdnOn.setEnabled(false);
    }
    
    
    
    public void enable(){
        TxtVisor.setEnabled(true);
        RdnOn.setEnabled(false);
        RdnOff.setEnabled(true);
        BtnUm.setEnabled(true);
        BtnDois.setEnabled(true);
        BtnTres.setEnabled(true);
        BtnQuatro.setEnabled(true);
        BtnCinco.setEnabled(true);
        BtnSeis.setEnabled(true);
        BtnSete.setEnabled(true);
        BtnOito.setEnabled(true);
        BtnNove.setEnabled(true);
        BtnZero.setEnabled(true);
        BtnMenos.setEnabled(true);
        BtnMais.setEnabled(true);
        BtnVezes.setEnabled(true);
        BtnDividir.setEnabled(true);
        BtnIgual.setEnabled(true);
        BtnLimpar.setEnabled(true);
        BtnPonto.setEnabled(true);
        
    }
    
    public void disable(){
        TxtVisor.setEnabled(false);
        RdnOn.setEnabled(true);
        RdnOff.setEnabled(false);
        BtnUm.setEnabled(false);
        BtnDois.setEnabled(false);
        BtnTres.setEnabled(false);
        BtnQuatro.setEnabled(false);
        BtnCinco.setEnabled(false);
        BtnSeis.setEnabled(false);
        BtnSete.setEnabled(false);
        BtnOito.setEnabled(false);
        BtnNove.setEnabled(false);
        BtnZero.setEnabled(false);
        BtnMenos.setEnabled(false);
        BtnMais.setEnabled(false);
        BtnVezes.setEnabled(false);
        BtnDividir.setEnabled(false);
        BtnIgual.setEnabled(false);
        BtnLimpar.setEnabled(false);
        BtnPonto.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TxtVisor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtnQuatro = new javax.swing.JButton();
        BtnZero = new javax.swing.JButton();
        BtnOito = new javax.swing.JButton();
        BtnPonto = new javax.swing.JButton();
        BtnNove = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnCinco = new javax.swing.JButton();
        BtnMenos = new javax.swing.JButton();
        BtnSeis = new javax.swing.JButton();
        BtnVezes = new javax.swing.JButton();
        BtnUm = new javax.swing.JButton();
        BtnDois = new javax.swing.JButton();
        RdnOn = new javax.swing.JRadioButton();
        RdnOff = new javax.swing.JRadioButton();
        BtnDividir = new javax.swing.JButton();
        BtnTres = new javax.swing.JButton();
        BtnSete = new javax.swing.JButton();
        BtnMais = new javax.swing.JButton();
        BtnLigar = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        TxtVisor.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        TxtVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtVisorActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        BtnQuatro.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnQuatro.setText("4");
        BtnQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuatroActionPerformed(evt);
            }
        });

        BtnZero.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnZero.setText("0");
        BtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnZeroActionPerformed(evt);
            }
        });

        BtnOito.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnOito.setText("8");
        BtnOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOitoActionPerformed(evt);
            }
        });

        BtnPonto.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnPonto.setText(".");
        BtnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPontoActionPerformed(evt);
            }
        });

        BtnNove.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnNove.setText("9");
        BtnNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNoveActionPerformed(evt);
            }
        });

        BtnIgual.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnIgual.setText("=");
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnCinco.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnCinco.setText("5");
        BtnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCincoActionPerformed(evt);
            }
        });

        BtnMenos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnMenos.setText("-");
        BtnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenosActionPerformed(evt);
            }
        });

        BtnSeis.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnSeis.setText("6");
        BtnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeisActionPerformed(evt);
            }
        });

        BtnVezes.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnVezes.setText("*");
        BtnVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVezesActionPerformed(evt);
            }
        });

        BtnUm.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnUm.setText("1");
        BtnUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUmActionPerformed(evt);
            }
        });

        BtnDois.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnDois.setText("2");
        BtnDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoisActionPerformed(evt);
            }
        });

        buttonGroup1.add(RdnOn);
        RdnOn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RdnOn.setText("ON");
        RdnOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdnOnActionPerformed(evt);
            }
        });

        buttonGroup1.add(RdnOff);
        RdnOff.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RdnOff.setText("OFF");
        RdnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdnOffActionPerformed(evt);
            }
        });

        BtnDividir.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnDividir.setText("/");
        BtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDividirActionPerformed(evt);
            }
        });

        BtnTres.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnTres.setText("3");
        BtnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTresActionPerformed(evt);
            }
        });

        BtnSete.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnSete.setText("7");
        BtnSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeteActionPerformed(evt);
            }
        });

        BtnMais.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BtnMais.setText("+");
        BtnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMaisActionPerformed(evt);
            }
        });

        BtnLigar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BtnLigar.setText("<--");
        BtnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLigarActionPerformed(evt);
            }
        });

        BtnLimpar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnLimpar.setText("C");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RdnOff)
                            .addComponent(RdnOn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnZero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnUm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnQuatro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnPonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnLimpar, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnVezes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RdnOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdnOff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtVisor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TxtVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        TxtVisor.setText("");
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDividirActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "/");
    }//GEN-LAST:event_BtnDividirActionPerformed

    private void BtnSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeteActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "7");
    }//GEN-LAST:event_BtnSeteActionPerformed

    private void BtnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuatroActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "4");
    }//GEN-LAST:event_BtnQuatroActionPerformed

    private void BtnOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOitoActionPerformed
       TxtVisor.setText(TxtVisor.getText() + "8");
    }//GEN-LAST:event_BtnOitoActionPerformed

    private void BtnNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNoveActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "9");
    }//GEN-LAST:event_BtnNoveActionPerformed

    private void BtnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCincoActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "5");
    }//GEN-LAST:event_BtnCincoActionPerformed

    private void BtnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeisActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "6");
    }//GEN-LAST:event_BtnSeisActionPerformed

    private void BtnVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVezesActionPerformed
       TxtVisor.setText(TxtVisor.getText() + "*");
    }//GEN-LAST:event_BtnVezesActionPerformed

    private void BtnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUmActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "1");
    }//GEN-LAST:event_BtnUmActionPerformed

    private void BtnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoisActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "2");
    }//GEN-LAST:event_BtnDoisActionPerformed

    private void BtnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTresActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "3");
    }//GEN-LAST:event_BtnTresActionPerformed

    private void BtnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaisActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "+");
    }//GEN-LAST:event_BtnMaisActionPerformed

    private void BtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnZeroActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "0");
    }//GEN-LAST:event_BtnZeroActionPerformed

    private void BtnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPontoActionPerformed
        TxtVisor.setText(TxtVisor.getText() + ".");
    }//GEN-LAST:event_BtnPontoActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenosActionPerformed
        TxtVisor.setText(TxtVisor.getText() + "-");
    }//GEN-LAST:event_BtnMenosActionPerformed

    private void TxtVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtVisorActionPerformed

    private void BtnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLigarActionPerformed
       
    }//GEN-LAST:event_BtnLigarActionPerformed

    private void RdnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdnOffActionPerformed
        disable();
    }//GEN-LAST:event_RdnOffActionPerformed

    private void RdnOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdnOnActionPerformed
        enable();
    }//GEN-LAST:event_RdnOnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCinco;
    private javax.swing.JButton BtnDividir;
    private javax.swing.JButton BtnDois;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnLigar;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnMais;
    private javax.swing.JButton BtnMenos;
    private javax.swing.JButton BtnNove;
    private javax.swing.JButton BtnOito;
    private javax.swing.JButton BtnPonto;
    private javax.swing.JButton BtnQuatro;
    private javax.swing.JButton BtnSeis;
    private javax.swing.JButton BtnSete;
    private javax.swing.JButton BtnTres;
    private javax.swing.JButton BtnUm;
    private javax.swing.JButton BtnVezes;
    private javax.swing.JButton BtnZero;
    private javax.swing.JRadioButton RdnOff;
    private javax.swing.JRadioButton RdnOn;
    private javax.swing.JTextField TxtVisor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
